[package]
name = "tower_governor"
authors = ["Ben Wishovich <ben@benw.is>"]
description = "A rate-limiting middleware for Tower backed by the governor crate that allows configurable key based and global limits"
repository = "https://github.com/benwis/tower-governor"
readme = "README.md"
version = "0.1.0"
edition = "2021"
keywords = ["axum", "tower", "tonic", "rate-limit", "governor"]
categories = ["web-programming::http-server"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.16"
forwarded-header-value = "0.1.1"
futures = "0.3.24"
futures-core = "0.3.24"
governor = "0.5.0"
http = "0.2.8"
pin-project = "1.0.12"
thiserror = "1.0.37"
tokio = { version = "0.2.22", features = ["full"] }
tower = "0.4.13"
tower-layer = "0.3.1"
tracing = "0.1.37"

[features]
# Enables tracing output for this middleware
tracing = []
